services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: firework-frontend
    ports:
      - "8045:8045"
    restart: "unless-stopped"
    networks:
      - firework-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: firework-backend
    ports:
      - "8080:80"
    restart: "unless-stopped"
    volumes:
      - sequences_data:/var/www/html
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    cap_add:
      - SYS_RAWIO
    networks:
      - firework-network

volumes:
  sequences_data:
    driver: local

networks:
  firework-network:
    driver: bridge
